server:
  address: 0.0.0.0
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.4.8:3306/mydatabase?serverTimezone=GMT%2b8
    username: zhanghan
    password: Zhanghan@123

mybatis:
  mapper-locations: classpath:./mapper/*.xml
