server:
  address: 0.0.0.0
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.97.14/MySQL?serverTimezone=GMT%2b8
    username: user
    password: Password123456

mybatis:
  mapper-locations: classpath:./mapper/*.xml
